### ISSUE TITLE
User Experience Improvement - Migration Completion

### ISSUE THREAD

**Issue by phillcoxon** [deliciousbrains/wp-migrate-db-pro-bugs#11]
![screen shot 2013-12-08 at 10 09 49 am](https://f.cloud.github.com/assets/60995/1699157/83230004-5f84-11e3-8389-98a63daae897.png)

Can I suggest making it a lot more apparent that a migration has been completed?  Right now the "Migration complete" note is very small and is over-powered by the progress bar below.   Many times I've glanced at this and thought the migration was almost completed but still going. 

I'd suggest:
- making the Migration Complete message far more prominent
- possibly hide the progress bar to avoid confusion?
- possibly add an additional "Click here to return to WordPress" or similar link at the bottom center to compliment the close icon in the top right. 

It's just a small thing I know but would improve user experience.

**Comment by tnorthcutt** [comment]
+1, many times I've assumed it was still going and switched back to another tab or application.

**Comment by theDanielJLewis** [comment]
I agree. Hide the progress bar and have a big button where they can close the progress panel.

**Comment by aprea** [comment]
Thanks for the feedback guys, I've logged this in our internal private issue tracker. We'll discuss this internally and probably include it in a future release.
