### ISSUE TITLE
Error Using Migrate 1.3b2

### ISSUE THREAD

**Issue by imagefact** [deliciousbrains/wp-migrate-db-pro-bugs#13]
Just a heads up that I tried using this with only:
Table: postmeta  
Post Type: page

And it messed up the transfer. I tried a few times and different options selected and couldn't get it to go smoothly. I only wanted pages moved over but it obviously moved more. 

Both sites are still using Wordpress 3.5.1 - not sure if that makes a difference?

**Comment by aprea** [comment]
Could you describe the actual problem you were having, was it this:

> I only wanted pages moved over but it obviously moved more. 

i.e. you selected only pages and only the postmeta table but it ended up migrating other tables?

**Comment by imagefact** [comment]
It's difficult to say, since I didn't have time to go hunting through the data. But I was moving from a development site to a production site and immediately I saw that nav menu's were messed up and posts weren't flowing in. So definitely more than just pages were changed.
