### ISSUE TITLE
1.3b2 doesn't get multisite media

### ISSUE THREAD

**Issue by theDanielJLewis** [deliciousbrains/wp-migrate-db-pro-bugs#14]
I have a large WordPress Multisite and WPMDP has worked and still works well for database stuff. But with both production and development servers running the same versions of everything, all the media was ignored.

Maybe this is similar to https://github.com/deliciousbrains/wp-migrate-db-pro-bugs/issues/4, because Multisite places the media in /wp-content/blogs.dir/[BLOG ID]/files/.

WordPress 3.7.1.

**Comment by aprea** [comment]
Thanks for report! Looking into it for you now.

**Comment by aprea** [comment]
@DanielJLewis, I've looked into this issue and I think I know whats going wrong here.

Pre WordPress 3.5, multisite used to use a directory called blogs.dir as it base directory for blog uploads. These days it uses the standard wp-content/uploads directory.

Even if you've upgraded from an older version of WordPress to a newer version it will continue using blogs.dir as the base for it's uploads.

Let me discuss this with the team to see if we can come up with a solution.

**Comment by theDanielJLewis** [comment]
Ah! I think this would be good for the plugin to handle. But I'll also investigate if there's a way I can change that on my network setup. I'd rather have the new way anyway.

**Comment by aprea** [comment]
Don't go to too much effort, I've coded up a solution, we're just testing it now.
