### ISSUE TITLE
Upgrading Media Files addon plugin before WP Migrate DB Pro borks WordPress

### ISSUE THREAD

**Issue by phillcoxon** [deliciousbrains/wp-migrate-db-pro-bugs#15]
I just logged into a site and saw new plugin releases for both WP Migrate DB Pro and the Media Files addon. 

I upgraded the Media files addon first which worked fine. 

I then tried to upgrade WP Migrate DB Pro and go the White Screen Of Death and the following error:  

Fatal error: Call to undefined method WPMDBPro_Media_Files::meets_version_requirements() in /home/petition/public_html/wp-content/plugins/wp-migrate-db-pro-media-files/class/wpmdbpro-media-files.php on line 7

The Admin dashboard was unavailable requiring logging into the server to move the Media Files addon out of the plugins directory.  I was then able to upgrade WP Migrate DB Pro just fine and move the Media Files addon folder back into the plugins directory. 

A check needed that forces users to upgrade WP Migrate DB Pro first?

**Comment by bradt** [comment]
Ah, yep, looks like this is a bug that only happens when you update in that order from the beta. Won't happen for anyone that didn't beta test. It's a non-issue for future upgrades as well since that method will always be defined in the WPMDBPro_Addon class of the core plugin.
