### ISSUE TITLE
Migrating Plugins From CLI

### ISSUE THREAD

**Issue by RichardTMiles** [deliciousbrains/wp-migrate-db-pro-bugs#18]
https://github.com/deliciousbrains/wp-migrate-db/issues/111

I'm trying to get eyes on this. It's not documented on your website and would really help me out.

**Comment by RichardTMiles** [comment]
@bradt

**Comment by polevaultweb** [comment]
See https://github.com/deliciousbrains/wp-migrate-db/issues/111#issuecomment-767424815
