### ISSUE TITLE
AJAX issue

### ISSUE THREAD

**Issue by curtismchale** [deliciousbrains/wp-migrate-db-pro-bugs#2]
Just upgraded to 1.3b1. When I try to push or pull a site I get this error

`There was a problem with the AJAX request, we were expecting a serialized response, instead we received: 0`

I'm running VVV locally and the site is on WPEngine.

Rolling back to the latest stable version ends up giving me errors as well.

`Notice: Undefined index: version in /srv/www/leaving-trails/wp-content/plugins/wp-migrate-db-pro/class/wp-migrate-db.php on line 2253`

**Comment by aprea** [comment]
Thanks for the report curtis. Just to confirm, when working with 1.3b1 did you first remove the existing copies of WP Migrate DB Pro on both the **local and remote** WordPress installations?

Both of these installations will need to be running 1.3b1.

As for the rollback error, unfortunately this is a little unavoidable. Though deleting a few transients should do the trick, if possible are you able to run the following code once:

``` php
delete_site_transient( 'update_plugins' );
delete_site_transient( 'wpmdb_upgrade_data' );
delete_site_transient( 'wpmdb_licence_response' );
```

**Comment by aprea** [comment]
@curtismchale just wondering if you've since looked into this at all?

**Comment by curtismchale** [comment]
@aprea bah, I'm included on a few big repos that I don't really follow (yeah don't ask).

Anyway I simply don't know at this point.

Not that it's helpful now.
