### ISSUE TITLE
Repeating a pull request with media 0/0 media files

### ISSUE THREAD

**Issue by helgatheviking** [deliciousbrains/wp-migrate-db-pro-bugs#3]
I'm not sure how this started, but I was using the beta to pull the media files to my staging site. Eventually, I was tracking down an error where WooCommerce was redirecting my checkout page from the staging site to the live site. 

Eventually I disabled WP Migrate and WP Migrate media add on and the checkout redirect resolved itself, but the media just kind of disappeared. I went in via FTP to delete everything, then did a WordPress "suicide" and then attempted to repeat the pull process.  

However, this time I keep getting 0/0 media items imported. 

![image](https://f.cloud.github.com/assets/507025/1650777/bab934c4-5aad-11e3-854a-94c756e9124a.png)

as a result all the images in the media library are broken

![image](https://f.cloud.github.com/assets/507025/1650862/97fc4002-5ab2-11e3-81b1-f0d2a04ce5bf.png)

**Comment by aprea** [comment]
If possible, are you able to remove the current (broken) media attachments using the media library on the staging site? You should be able to select all the attachments and bulk delete them.

If so, are you able to run another pull migration afterwards and let me know what happens?

**Comment by helgatheviking** [comment]
I think I actually tried that once, and just did it again. Still get 0/0 media images and the broken media attachments.

**Comment by aprea** [comment]
Thanks for this! We're currently in the process of pushing out a beta update that includes better error reporting.

This will probably help us diagnose the issue a little easier. I'll leave another message in this thread when the update is ready to download.

**Comment by aprea** [comment]
We've just released the update, are you able to go to the plugins page into your WordPress dashboard and update the media files addon from there?
