### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by dmje** [deliciousbrains/wp-migrate-db-pro-bugs#5]
Hi - I get this error in the plugin list:

Notice: Undefined index: wp-migrate-db-pro-media-files in /Users/Mike/Sites/mysite.local/wp-content/plugins/wp-migrate-db-pro/class/wpmdbpro-base.php on line 495

cheers

Mike

**Comment by aprea** [comment]
Hi @dmje, this sounds like it could have been a caching problem. Are you still experiencing this issue?

**Comment by dmje** [comment]
Hi Chris

I think it’s sorted now - thanks for getting back. Will report it again if it continues

Mike  

---

mike@thirty8.co.uk (mailto:mike@thirty8.co.uk)
thirty8: a small but perfectly formed digital agency

Tel: 0800 808 54 38
Mob: 07810 487 423
Web: thirty8.co.uk (http://thirty8.co.uk/)
