### ISSUE TITLE
Green Plugin Background is kind of irritating

### ISSUE THREAD

**Issue by tordans** [deliciousbrains/wp-migrate-db-pro-bugs#6]
This is a minor thing:

The green background suggests "its installed" when in fact its the list of "avaliable for install" plugins.

Maybe follow the wordpress-styleguide a little more closely for this.

![bildschirmfoto 2013-12-06 um 13 43 52](https://f.cloud.github.com/assets/111561/1692177/56a533a0-5e74-11e3-9267-e7105019da3f.png)

**Comment by bradt** [comment]
Thanks for your opinion on this.
