### ISSUE TITLE
Add advanced migration options: "Set 'hide from google' to true/false"

### ISSUE THREAD

**Issue by tordans** [deliciousbrains/wp-migrate-db-pro-bugs#8]
My staging and production run on the same server with subdomains. 
On production the wordpress-setting "hide from google" is set to false, on staging to true.

Is would be great to have a advanced migration setting that forces a true/false for this setting, so I dont have to check it after each migration.

![bildschirmfoto 2013-12-06 um 13 56 28](https://f.cloud.github.com/assets/111561/1692250/1cbdabca-5e76-11e3-96f4-3f68df3c1864.png)

**Comment by tordans** [comment]
Actually, I can probably do this with one of the replace-rules, right? Will have to check that out …

**Comment by tordans** [comment]
No, that does not work. Its in the wp_options-Table, option_name 'blog_public', option_value: '0' / '1'.
So I cannot replace it with the find-replace, right?

**Comment by bradt** [comment]
You can accomplish this with the `wpmdb_preserved_options` filter:
https://deliciousbrains.com/tweaking-wp-migrate-db-pro-actions-filters/
