### ISSUE TITLE
Check directory permissions for files-folders before migrating

### ISSUE THREAD

**Issue by tordans** [deliciousbrains/wp-migrate-db-pro-bugs#9]
I just migrated the images from staging to development.
First time I got a big red error message about directory permission.

It would be great if the plugin checked those prior to the migration and provides a message that is easier to read than the one you get right now.

PS. after fixing this the migration worked great! awesome! (Had to delete the existing folder with files though … will check with my next migrations if that was a one time thing or a bug.)

**Comment by bradt** [comment]
Good idea! Added to our internal issue tracker.
